name: Deploy to Production

# ⚠️ IMPORTANT: Customize for your deployment
# 1. Set GitHub Secrets: DEPLOY_HOST, DEPLOY_USER, DEPLOY_KEY
# 2. Update the 'cd' path below to your project directory
# See docs/DEPLOYMENT_CONFIG.md for full setup guide

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/kyanwick/saas/saas
            git fetch origin master
            git reset --hard origin/master
            ./scripts/deploy.sh
